name: Build PDFs & Release

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths:
      - '**.md'
      - '**.bib'
      - '**.tex'
      - '**.csl'
      - '**.theme'
      - 'Makefile'
      - '**/Makefile'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Set up Miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Miniforge3
          auto-update-conda: true
          activate-environment: build-env
          environment-file: ""
          auto-activate-base: false

      - name: Install Pandoc
        shell: bash -l {0}
        run: |
          conda install -y -c conda-forge pandoc==3.9

      - name: Install Tex & Fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          texlive-xetex texlive-latex-extra texlive-fonts-recommended \
          fonts-liberation \
          fonts-hack

      - name: Build all PDFs
        shell: bash -l {0}
        run: make

      - name: Collect PDFs With Structure
        run: |
          mkdir output
          find . \( -name "*.pdf" -o -name "*.mp4" \) -not -path "./output/*" | while read file; do
            cp --parents "${file#./}" output/
          done

      - name: Set date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Create zip
        run: |
          cd output
          zip -r ../${DATE}-submissions.zip .

      - name: Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.DATE }}
          name: ${{ env.DATE }}-submissions.zip
          files: ${{ env.DATE }}-submissions.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}